pipeline {
    agent any
    environment {
        appName = 'variable'
    }
    stages {
        stage('Train Model') {
            steps {
                script {
                    sh "python3 ml-project/train.py"
                }
            }
        }
        stage('Deploy FastAPI') {
            steps {
                script {
                    sh "docker build -t my-model-api:latest ml-project/."
                    sh "docker run -d --name my-model-api-container -p 8000:8000 my-model-api"
                }
            }
        }
    }
    post {
        always {
            deleteDir()
            sh "echo 'Cleaning up workspace'"
        }
        success {
            sh "echo 'Deployment successful'"
        }
        failure {
            sh "echo 'Deployment failed'"
        }
    }
}
